# Generated by Django 6.1 on 2026-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='رمز عبور خام (جهت مشاهده مدیر و منشی)'),
        ),
    ]
