# Generated by Django 6.1 on 2026-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_birth_date_user_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس والدین'),
        ),
    ]
