# Generated by Django 6.1 on 2026-08-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=45, verbose_name='مدت زمان آزمون (دقیقه)'),
        ),
    ]
