# Generated by Django 6.1 on 2026-08-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.FloatField(default=1.0, verbose_name='بارم نمره سوال'),
        ),
    ]
