# Generated by Django 6.1 on 2026-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(default='20:00', verbose_name='ساعت پایان مهلت شروع آزمون'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(default='18:00', verbose_name='ساعت شروع مهلت آزمون'),
        ),
    ]
