# Generated by Django 6.1 on 2026-08-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='tuition_fee',
            field=models.PositiveIntegerField(default=2500000, verbose_name='شهریه کلاس (تومان)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت شهریه'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات و یادداشت پرداخت'),
        ),
    ]
