# Generated by Django 6.1 on 2026-08-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classroom_tuition_fee_enrollment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='schedule',
            field=models.CharField(blank=True, default='روزهای زوج (شنبه، دوشنبه، چهارشنبه)', max_length=150, null=True, verbose_name='برنامه و روزهای برگزاری'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='time_slot',
            field=models.CharField(blank=True, default='۱۶:۰۰ الی ۱۷:۳۰', max_length=100, null=True, verbose_name='ساعت برگزاری'),
        ),
    ]
