name: Network Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test network
        run: |
          echo "Testing server..."
          timeout 10 bash -c '</dev/tcp/78.157.61.183/22' && echo "PORT 22 OPEN" || echo "PORT 22 BLOCKED"
